Read Collection Pickle

In [1]:
import numpy as np
import pandas as pd

# 1) Download the collection set from the Gitlab repository: https://gitlab.com/checkthat_lab/clef2025-checkthat-lab/-/tree/main/task4?ref_type=heads
# 2) Drag and drop the downloaded file to the "Files" section (left vertical menu on Colab)
# 3) Modify the path to your local file path
PATH_COLLECTION_DATA = '/home/guilherme/workspace/feup-ir-project/data/subtask_4b/subtask4b_collection_data.pkl' #MODIFY PATH
df_collection = pd.read_pickle(PATH_COLLECTION_DATA)
df_collection.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7718 entries, 162 to 1056448
Data columns (total 17 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   cord_uid          7718 non-null   object
 1   source_x          7718 non-null   object
 2   title             7718 non-null   object
 3   doi               7677 non-null   object
 4   pmcid             4959 non-null   object
 5   pubmed_id         6233 non-null   object
 6   license           7718 non-null   object
 7   abstract          7718 non-null   object
 8   publish_time      7715 non-null   object
 9   authors           7674 non-null   object
 10  journal           6668 non-null   object
 11  mag_id            0 non-null      float64
 12  who_covidence_id  528 non-null    object
 13  arxiv_id          20 non-null     object
 14  label             7718 non-null   object
 15  time              7715 non-null   datetime64[ns]
 16  timet             7718 non-null   int64
dtypes: datetime64[ns](1), float64(1), int64(1), object(14)
memory usage: 1.1+ MB

In [2]:
df_collection.head()

,cord_uid,source_x,title,doi,pmcid,pubmed_id,license,abstract,publish_time,authors,journal,mag_id,who_covidence_id,arxiv_id,label,time,timet
162,umvrwgaw,PMC,Professional and Home-Made Face Masks Reduce E...,10.1371/journal.pone.0002618,PMC2440799,18612429,cc-by,BACKGROUND: Governments are preparing for a po...,2008-07-09,"van der Sande, Marianne; Teunis, Peter; Sabel,...",PLoS One,NaN,NaN,NaN,umvrwgaw,2008-07-09,1215561600
611,spiud6ok,PMC,The Failure of R (0),10.1155/2011/527610,PMC3157160,21860658,cc-by,"The basic reproductive ratio, R (0), is one of...",2011-08-16,"Li, Jing; Blakeley, Daniel; Smith?, Robert J.",Comput Math Methods Med,NaN,NaN,NaN,spiud6ok,2011-08-16,1313452800
918,aclzp3iy,PMC,Pulmonary sequelae in a patient recovered from...,10.4103/0970-2113.99118,PMC3424870,22919170,cc-by-nc-sa,The pandemic of swine flu (H1N1) influenza spr...,2012,"Singh, Virendra; Sharma, Bharat Bhushan; Patel...",Lung India,NaN,NaN,NaN,aclzp3iy,2012-01-01,1325376000
993,ycxyn2a2,PMC,What was the primary mode of smallpox transmis...,10.3389/fcimb.2012.00150,PMC3509329,23226686,cc-by,The mode of infection transmission has profoun...,2012-11-29,"Milton, Donald K.",Front Cell Infect Microbiol,NaN,NaN,NaN,ycxyn2a2,2012-11-29,1354147200
1053,zxe95qy9,PMC,"Lessons from the History of Quarantine, from P...",10.3201/eid1902.120312,PMC3559034,23343512,no-cc,"In the new millennium, the centuries-old strat...",2013-02-03,"Tognotti, Eugenia",Emerg Infect Dis,NaN,NaN,NaN,zxe95qy9,2013-02-03,1359849600

Process Query File

In [3]:
# 1) Download the query tweets from the Gitlab repository: https://gitlab.com/checkthat_lab/clef2025-checkthat-lab/-/tree/main/task4?ref_type=heads
# 2) Drag and drop the downloaded file to the "Files" section (left vertical menu on Colab)
# 3) Modify the path to your local file path
PATH_QUERY_DATA = '/home/guilherme/workspace/feup-ir-project/data/subtask_4b/subtask4b_query_tweets.tsv' #MODIFY PATH
df_query = pd.read_csv(PATH_QUERY_DATA, sep = '\t')
df_query.head()

                                          tweet_text  cord_uid
0  Oral care in rehabilitation medicine: oral vul...  htlvpvz5
1  this study isn't receiving sufficient attentio...  4kfl29ul
2  thanks, xi jinping. a reminder that this study...  jtwb17u8
3  Taiwan - a population of 23 million has had ju...  0w9k8iy1
4  Obtaining a diagnosis of autism in lower incom...  tiqksd69

In [4]:
df_query.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14253 entries, 0 to 14252
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   tweet_text  14253 non-null  object
 1   cord_uid    14253 non-null  object
dtypes: object(2)
memory usage: 222.8+ KB

In [5]:
from sklearn.model_selection import train_test_split

TRAINING_SPLIT_SIZE = 0.8

df_training_set, df_test_set = train_test_split(df_query, test_size=0.2)

print("--- Training")
df_training_set.info()
print("--- Test")
df_test_set.info()

--- Training
<class 'pandas.core.frame.DataFrame'>
Index: 11402 entries, 967 to 737
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   tweet_text  11402 non-null  object
 1   cord_uid    11402 non-null  object
dtypes: object(2)
memory usage: 267.2+ KB
--- Test
<class 'pandas.core.frame.DataFrame'>
Index: 2851 entries, 11583 to 1434
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   tweet_text  2851 non-null   object
 1   cord_uid    2851 non-null   object
dtypes: object(2)
memory usage: 66.8+ KB

In [6]:
df_training_set.head()

                                              tweet_text  cord_uid
967    A peer-reviewed study reveals no substantial a...  texmsvyt
1999   just read the section titled explanation... yo...  a7frertc
1081   A University of Washington study discovered th...  lp0r7j5c
2304   In this convenience sample survey disseminated...  iucrorzh
13517  Long Covid - innate versus vaccine immunity di...  ivue7zob

In [7]:
df_collection.head()

,cord_uid,source_x,title,doi,pmcid,pubmed_id,license,abstract,publish_time,authors,journal,mag_id,who_covidence_id,arxiv_id,label,time,timet
162,umvrwgaw,PMC,Professional and Home-Made Face Masks Reduce E...,10.1371/journal.pone.0002618,PMC2440799,18612429,cc-by,BACKGROUND: Governments are preparing for a po...,2008-07-09,"van der Sande, Marianne; Teunis, Peter; Sabel,...",PLoS One,NaN,NaN,NaN,umvrwgaw,2008-07-09,1215561600
611,spiud6ok,PMC,The Failure of R (0),10.1155/2011/527610,PMC3157160,21860658,cc-by,"The basic reproductive ratio, R (0), is one of...",2011-08-16,"Li, Jing; Blakeley, Daniel; Smith?, Robert J.",Comput Math Methods Med,NaN,NaN,NaN,spiud6ok,2011-08-16,1313452800
918,aclzp3iy,PMC,Pulmonary sequelae in a patient recovered from...,10.4103/0970-2113.99118,PMC3424870,22919170,cc-by-nc-sa,The pandemic of swine flu (H1N1) influenza spr...,2012,"Singh, Virendra; Sharma, Bharat Bhushan; Patel...",Lung India,NaN,NaN,NaN,aclzp3iy,2012-01-01,1325376000
993,ycxyn2a2,PMC,What was the primary mode of smallpox transmis...,10.3389/fcimb.2012.00150,PMC3509329,23226686,cc-by,The mode of infection transmission has profoun...,2012-11-29,"Milton, Donald K.",Front Cell Infect Microbiol,NaN,NaN,NaN,ycxyn2a2,2012-11-29,1354147200
1053,zxe95qy9,PMC,"Lessons from the History of Quarantine, from P...",10.3201/eid1902.120312,PMC3559034,23343512,no-cc,"In the new millennium, the centuries-old strat...",2013-02-03,"Tognotti, Eugenia",Emerg Infect Dis,NaN,NaN,NaN,zxe95qy9,2013-02-03,1359849600

In [8]:
positive_train_data = pd.DataFrame(columns=df_collection.columns)
query = []
for idx, row in df_training_set.iterrows():
    entry_cord_id = row.cord_uid
    query.append(row.tweet_text)
    positive_train_data = pd.concat([positive_train_data, df_collection.loc[df_collection["cord_uid"] == entry_cord_id]], ignore_index=True)

cls = [1] * len(positive_train_data)
positive_train_data["class"] = cls
positive_train_data["query"] = query
positive_train_data.info()

/tmp/ipykernel_4039/1805405490.py:6: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  positive_train_data = pd.concat([positive_train_data, df_collection.loc[df_collection["cord_uid"] == entry_cord_id]], ignore_index=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11402 entries, 0 to 11401
Data columns (total 19 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   cord_uid          11402 non-null  object
 1   source_x          11402 non-null  object
 2   title             11402 non-null  object
 3   doi               11349 non-null  object
 4   pmcid             7540 non-null   object
 5   pubmed_id         9382 non-null   object
 6   license           11402 non-null  object
 7   abstract          11402 non-null  object
 8   publish_time      11398 non-null  object
 9   authors           11334 non-null  object
 10  journal           9892 non-null   object
 11  mag_id            0 non-null      object
 12  who_covidence_id  637 non-null    object
 13  arxiv_id          43 non-null     object
 14  label             11402 non-null  object
 15  time              11398 non-null  datetime64[ns]
 16  timet             11402 non-null  object
 17  class             11402 non-null  int64
 18  query             11402 non-null  object
dtypes: datetime64[ns](1), int64(1), object(17)
memory usage: 1.7+ MB

In [9]:
positive_test_data = pd.DataFrame(columns=df_collection.columns)
query = []
for idx, row in df_test_set.iterrows():
    entry_cord_id = row.cord_uid
    query.append(row.tweet_text)
    positive_test_data = pd.concat([positive_test_data, df_collection.loc[df_collection["cord_uid"] == entry_cord_id]], ignore_index=True)

cls = [1] * len(positive_test_data)
positive_test_data["class"] = cls
positive_test_data["query"] = query
positive_test_data.info()

/tmp/ipykernel_4039/861200239.py:6: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  positive_test_data = pd.concat([positive_test_data, df_collection.loc[df_collection["cord_uid"] == entry_cord_id]], ignore_index=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2851 entries, 0 to 2850
Data columns (total 19 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   cord_uid          2851 non-null   object
 1   source_x          2851 non-null   object
 2   title             2851 non-null   object
 3   doi               2839 non-null   object
 4   pmcid             1829 non-null   object
 5   pubmed_id         2320 non-null   object
 6   license           2851 non-null   object
 7   abstract          2851 non-null   object
 8   publish_time      2850 non-null   object
 9   authors           2836 non-null   object
 10  journal           2446 non-null   object
 11  mag_id            0 non-null      object
 12  who_covidence_id  192 non-null    object
 13  arxiv_id          5 non-null      object
 14  label             2851 non-null   object
 15  time              2850 non-null   datetime64[ns]
 16  timet             2851 non-null   object
 17  class             2851 non-null   int64
 18  query             2851 non-null   object
dtypes: datetime64[ns](1), int64(1), object(17)
memory usage: 423.3+ KB

In [10]:
NUM_NEGATIVE_SAMPLES = 5

negative_train_data = pd.DataFrame(columns=df_collection.columns)
query = []

for idx, row in df_training_set.iterrows():
    entry_cord_id = row.cord_uid
    repeated_queries = [row.tweet_text] * NUM_NEGATIVE_SAMPLES
    query += repeated_queries
    negative_samples = df_collection.loc[df_collection["cord_uid"] != entry_cord_id]
    negative_samples = negative_samples.sample(NUM_NEGATIVE_SAMPLES)
    negative_train_data = pd.concat([negative_train_data, negative_samples], ignore_index=True)

cls = [0] * len(negative_train_data)
negative_train_data["class"] = cls
negative_train_data["query"] = query
negative_train_data.head()

/tmp/ipykernel_4039/387010300.py:12: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  negative_train_data = pd.concat([negative_train_data, negative_samples], ignore_index=True)

,cord_uid,source_x,title,doi,pmcid,pubmed_id,license,abstract,publish_time,authors,journal,mag_id,who_covidence_id,arxiv_id,label,time,timet,class,query
0,ziyzdcmg,Medline; PMC,The association between food insecurity and me...,10.1186/s12889-021-10631-0,PMC8006138,33781232,no-cc,OBJECTIVE: To explore the association between ...,2021-03-29,"Fang, Di; Thomsen, Michael R.; Nayga, Rodolfo M.",BMC Public Health,NaN,NaN,NaN,ziyzdcmg,2021-03-29,1616976000,0,A peer-reviewed study reveals no substantial a...
1,yfpioqi5,Medline; PMC,Zn(2+) Inhibits Coronavirus and Arterivirus RN...,10.1371/journal.ppat.1001176,PMC2973827,21079686,cc-by,Increasing the intracellular Zn(2+) concentrat...,2010-11-04,"te Velthuis, Aartjan J. W.; van den Worm, Sjoe...",PLoS Pathog,NaN,NaN,NaN,yfpioqi5,2010-11-04,1288828800,0,A peer-reviewed study reveals no substantial a...
2,sgwvid9l,Elsevier; Medline; PMC; WHO,Memory B Cell Repertoire for Recognition of Ev...,10.1016/j.cell.2021.07.025,PMC8299219,34332650,els-covid,Memory B cell reserves can generate protective...,2021-07-23,"Tong, Pei; Gautam, Avneesh; Windsor, Ian W.; T...",Cell,NaN,NaN,NaN,sgwvid9l,2021-07-23,1626998400,0,A peer-reviewed study reveals no substantial a...
3,m1glq4ac,Medline; PMC; WHO,Mental Health Over Time and Financial Concerns...,10.1007/s11469-021-00750-5,PMC8772534,35079239,no-cc,This study examined online gambling behavior d...,2022-01-20,"Price, Alex; Tabri, Nassim; Stark, Sasha; Balo...",Int J Ment Health Addict,NaN,NaN,NaN,m1glq4ac,2022-01-20,1642636800,0,A peer-reviewed study reveals no substantial a...
4,69ly7gp4,Medline; PMC,Reconstruction of ancient microbial genomes fr...,10.1038/s41586-021-03532-0,PMC8189908,33981035,cc-by,Loss of gut microbial diversity(1–6) in indust...,2021-05-12,"Wibowo, Marsha C.; Yang, Zhen; Borry, Maxime; ...",Nature,NaN,NaN,NaN,69ly7gp4,2021-05-12,1620777600,0,A peer-reviewed study reveals no substantial a...

In [15]:
NUM_NEGATIVE_SAMPLES = 5

negative_test_data = pd.DataFrame(columns=df_collection.columns)
query = []

for idx, row in df_test_set.iterrows():
    entry_cord_id = row.cord_uid
    repeated_queries = [row.tweet_text] * NUM_NEGATIVE_SAMPLES
    query += repeated_queries
    negative_samples = df_collection.loc[df_collection["cord_uid"] != entry_cord_id]
    negative_samples = negative_samples.sample(NUM_NEGATIVE_SAMPLES)
    negative_test_data = pd.concat([negative_test_data, negative_samples], ignore_index=True)

cls = [0] * len(negative_test_data)
negative_test_data["class"] = cls
negative_test_data["query"] = query
negative_test_data.head()

/tmp/ipykernel_4039/1904492962.py:12: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  negative_test_data = pd.concat([negative_test_data, negative_samples], ignore_index=True)

,cord_uid,source_x,title,doi,pmcid,pubmed_id,license,abstract,publish_time,authors,journal,mag_id,who_covidence_id,arxiv_id,label,time,timet,class,query
0,2fryixdh,PMC,Chemogenetic Inhibition of Infralimbic Prefron...,10.1523/eneuro.0423-19.2020,PMC7598911,33055196,cc-by,Hypofunction of the prefrontal cortex (PFC) co...,2020-10-26,"Nawreen, Nawshaba; Cotella, Evelin M.; Morano,...",eNeuro,NaN,NaN,NaN,2fryixdh,2020-10-26,1603670400,0,"5. ""we did not discover evidence that surgical..."
1,94rcj9nc,Elsevier; Medline; PMC,The Impact of COVID-19 related Measures on the...,10.1016/j.joule.2020.06.009,PMC7303630,32835175,els-covid,Abstract: Restrictions enacted to reduce the s...,2020-06-19,"Peters, Ian Marius; Brabec, Christoph; Buonass...",Joule,NaN,NaN,NaN,94rcj9nc,2020-06-19,1592524800,0,"5. ""we did not discover evidence that surgical..."
2,898oxxqi,Elsevier; Medline; PMC,SARS-CoV-2 mRNA vaccination induces functional...,10.1016/j.cell.2021.06.005,PMC8185186,34192529,els-covid,In this study we profiled vaccine-induced poly...,2021-06-08,"Amanat, Fatima; Thapa, Mahima; Lei, Tinting; S...",Cell,NaN,NaN,NaN,898oxxqi,2021-06-08,1623110400,0,"5. ""we did not discover evidence that surgical..."
3,dccymlie,Medline; PMC,Analysis of Asymptomatic and Presymptomatic Tr...,10.3201/eid2704.204576,PMC8007320,33600301,no-cc,We determined secondary attack rates (SAR) amo...,2021-04-03,"Bender, Jennifer K.; Brandl, Michael; Höhle, M...",Emerg Infect Dis,NaN,NaN,NaN,dccymlie,2021-04-03,1617408000,0,"5. ""we did not discover evidence that surgical..."
4,7m33mjl1,Medline; PMC,The Chemo-Gut Pilot Study: Associations betwee...,10.3390/curroncol29050243,PMC9140183,35621633,cc-by,Chemotherapy adversely affects the gut microbi...,2022-04-21,"Deleemans, Julie M.; Chleilat, Faye; Reimer, R...",Curr Oncol,NaN,NaN,NaN,7m33mjl1,2022-04-21,1650499200,0,"5. ""we did not discover evidence that surgical..."

In [13]:
mixed_training_set = pd.concat([negative_train_data, positive_train_data], ignore_index=True)
mixed_training_set.info()

mixed_training_set.to_csv('data/train/tweets-query-pairs.tsv',sep='\t')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 68412 entries, 0 to 68411
Data columns (total 19 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   cord_uid          68412 non-null  object
 1   source_x          68412 non-null  object
 2   title             68412 non-null  object
 3   doi               68061 non-null  object
 4   pmcid             44105 non-null  object
 5   pubmed_id         55336 non-null  object
 6   license           68412 non-null  object
 7   abstract          68412 non-null  object
 8   publish_time      68392 non-null  object
 9   authors           68051 non-null  object
 10  journal           59016 non-null  object
 11  mag_id            0 non-null      object
 12  who_covidence_id  4543 non-null   object
 13  arxiv_id          193 non-null    object
 14  label             68412 non-null  object
 15  time              68392 non-null  datetime64[ns]
 16  timet             68412 non-null  object
 17  class             68412 non-null  int64
 18  query             68412 non-null  object
dtypes: datetime64[ns](1), int64(1), object(17)
memory usage: 9.9+ MB

In [16]:
mixed_test_set = pd.concat([negative_test_data, positive_test_data], ignore_index=True)
mixed_test_set.info()

mixed_test_set.to_csv('data/test/tweets-query-pairs.tsv',sep='\t')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17106 entries, 0 to 17105
Data columns (total 19 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   cord_uid          17106 non-null  object
 1   source_x          17106 non-null  object
 2   title             17106 non-null  object
 3   doi               17018 non-null  object
 4   pmcid             10964 non-null  object
 5   pubmed_id         13794 non-null  object
 6   license           17106 non-null  object
 7   abstract          17106 non-null  object
 8   publish_time      17097 non-null  object
 9   authors           17024 non-null  object
 10  journal           14736 non-null  object
 11  mag_id            0 non-null      object
 12  who_covidence_id  1172 non-null   object
 13  arxiv_id          45 non-null     object
 14  label             17106 non-null  object
 15  time              17097 non-null  datetime64[ns]
 16  timet             17106 non-null  object
 17  class             17106 non-null  int64
 18  query             17106 non-null  object
dtypes: datetime64[ns](1), int64(1), object(17)
memory usage: 2.5+ MB